services:
  db:
    image: postgres:16
    container_name: clinicbooking-db
    environment:
      POSTGRES_DB: clinicbooking
      POSTGRES_USER: clinic
      POSTGRES_PASSWORD: clinicpass
    ports:
      - "5432:5432"
    volumes:
      - clinicbooking_pgdata:/var/lib/postgresql/data

volumes:
  clinicbooking_pgdata:
